### ISSUE TITLE
module5 tests missing check for href equal sign

### ISSUE THREAD

**Issue by ToniCipriani** [pluralsight-projects/PythonFlask-JobBoard#12]
Made a mistake omitting an equal sign in the href update

`<a href {{ url_for('job',job_id=job['id']) }}>{{ job['title'] }}</a>`

Instead of

`<a href={{ url_for('job',job_id=job['id']) }}>{{ job['title'] }}</a>`

And the assert check did not catch the missing = sign:

`assert 'job:job_id:job:id' in template_functions('_macros', 'url_for'), 'Looks like the job title link `href` is incorrect.'`

**Comment by tjbell** [comment]
Thanks for the report. I see what I can do.
