### ISSUE TITLE
test_app_review_post_request_check_module7() cannot pass until entire module complete

### ISSUE THREAD

**Issue by judithowens** [pluralsight-projects/PythonFlask-JobBoard#18]
One of the assertions in this test (associated with part 2 of module 7):

`assert employer in return_values, 'Did you return a call to `redirect` and `url_for`?'`

cannot be true until after completing part 5 Redirect to Employer Page, as we don't code in the redirect until this point. I've fixed the code on my fork by moving the assertion so I can complete the module but it needs propagating to the main repo.

**Comment by tjbell** [comment]
@judithowens Thank you for the feedback. I'll see if I can get this added.
