### ISSUE TITLE
index.html not rendering in module2 and module3

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/PythonFlask-JobBoard#22]
**modules:** [module2, "Base Template and Styling"](https://app.pluralsight.com/projects/build-a-job-board-with-python-flask/base-template-and-styling) (and [module3, "Preparing for Dynamic Content"](https://app.pluralsight.com/projects/build-a-job-board-with-python-flask/preparing-for-dynamic-content))

**issue:** The main page, index.html, does not render anything
- this is due to there being no block content section
- Users expect there to be something shown, as the last Task in https://app.pluralsight.com/projects/build-a-job-board-with-python-flask/base-template-and-styling says there will be

**reports:**
- I _think_ I noticed this during beta (been awhile, can't guarantee it)
- At least one, likely two other users noticed this and were thrown:  https://app.pluralsight.com/projects/build-a-job-board-with-python-flask/discussion#comment-4530913018

**suggested fixes:** Very loose, as likely a bit more testing will need to be done
- Have a new second-last Task in  https://app.pluralsight.com/projects/build-a-job-board-with-python-flask/base-template-and-styling that as users add a block content section to jobs/templates/index.html
  ```
  {% extends 'layout.html' %}
  {% block content %}
  <h1>Jobs</h1>
  {% endblock %}
  ```
- Reword the current last task to say Jobs will appear indented a bit and with a nicer font
- You'll need to updated any later Tasks accordingly.  e.g., https://app.pluralsight.com/projects/build-a-job-board-with-python-flask/display-all-jobs Task 10, "Index Template"

**Comment by tjbell** [comment]
Task was reworded.
