### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jorge0903** [pluralsight-projects/PythonFlask-JobBoard#8]
The instructions are not working while using OSX
pytest returns errors
flask run returns: flask.cli.NoAppException

**Comment by jorge0903** [comment]
These commands solved my issue:
    pip install virtualenv
    virtualenv ./venv
    source venv/bin/activate
    pip install -r requirements.txt
    pip install pytest-json-report --upgrade 

See current requirements:
[requirements.txt](https://github.com/pluralsight-projects/PythonFlask-JobBoard/files/2799514/requirements.txt)

**Comment by tjbell** [comment]
@jorge0903 All take a look at this. Thanks for the report.

**Comment by muzahidhassan92** [comment]
@jorge0903 Any update on this issue

**Comment by tjbell** [comment]
If you are on Windows you can use `python -m flask run`.

**Comment by nsanjuan** [comment]
I am just starting to follow along with this project and python -m flask run doesn't work either. Any other suggestions and maybe can you update the material if it's not up to date? thanks!!

**Comment by DhyaneshNaik** [comment]
flask.cli.NoAppException: Failed to find Flask application or factory in module "jobs.app". Use "FLASK_APP=jobs.app:name to specify one.

Traceback (most recent call last)
File "C:\Users\DELL\Using Flask\ProjectRoot\venv\Lib\site-packages\flask\cli.py", line 97, in find_best_app
raise NoAppException(
flask.cli.NoAppException: Failed to find Flask application or factory in module "jobs.app". Use "FLASK_APP=jobs.app:name to specify one.

I encountered the same issue. Could you please help?

**Comment by kirankotari** [comment]
@DhyaneshNaik @nsanjuan its expected bug due to your haven't wrote anything as per the task. At the of session i.e. Flask Setup the issue will be resolved.

@tjbell Please mention to ignore the error and go further to resolve the issue and I suggest don't confuse the students please.
